name: Release Doctor
on:
  pull_request:
  workflow_dispatch:

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-latest
    if: github.repository == 'meorphis-test/test-repo-3' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch' || startsWith(github.head_ref, 'release-please') || github.head_ref == 'next')

    steps:
      - uses: actions/checkout@v3

      - name: Check release environment
        run: |
          bash ./bin/check-release-environment
        env:
          SONATYPE_USERNAME: ${{ secrets.MEORPHIS_TEST_6_SONATYPE_USERNAME || secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.MEORPHIS_TEST_6_SONATYPE_PASSWORD || secrets.SONATYPE_PASSWORD }}
          GPG_SIGNING_KEY_ID: ${{ secrets.MEORPHIS_TEST_6_SONATYPE_GPG_SIGNING_KEY_ID || secrets.GPG_SIGNING_KEY_ID }}
          GPG_SIGNING_KEY: ${{ secrets.MEORPHIS_TEST_6_SONATYPE_GPG_SIGNING_KEY || secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.MEORPHIS_TEST_6_SONATYPE_GPG_SIGNING_PASSWORD || secrets.GPG_SIGNING_PASSWORD }}
